### ISSUE TITLE
Multinode Architecture on AWS

### ISSUE THREAD

**Issue by tlxnithin** [blockapps/aws-getting-started#4]
I am having two instances of AWS EC2 STRATO nodes, and I want them to connect across a single network. Currently is it possible to do something like this? If so how? I have been researching and have not found proper documentation anywhere for the multi-node deployment.

If not, then what is the use of having single node? As per my knowledge STRATO node is nothing but a ethereum node with API wrapped around it and many features like SQL, Apex. Correct me if I am wrong.

Hoping to get the knowledge and the information I am seeking for.

**Comment by cenbiliu** [comment]
Yes. For multi-node network setup, you may follow instructions [here](https://github.com/blockapps/strato-getting-started). Additionally, with our imminent 4.0 release, multinode network will be more performant. I'd be happy to correspond with you further on your multi node use case.

**Comment by cenbiliu** [comment]
what did you experience with the aforementioned instructions for multinode?

**Comment by tlxnithin** [comment]
AWS EC2 Blockapps has the script of older version where it doesn't even have the attribute of BOOT_NODE_IP. Even if you specify it wont change anything. So for planning to take the new code and put in those instances and test.

**Comment by tlxnithin** [comment]
Looks like that is not possible. AWS EC2 STARTO nodes currently do not support multinode I think. Please let me know if it is possible.

**Comment by cenbiliu** [comment]
I'd suggest to try our[ latest release](https://github.com/blockapps/strato-getting-started/releases) locally first. With our cloud partnership, we do need to go through a process to upgrade. We can also talk about how to deploy test nodes if it's a large project.

**Comment by tlxnithin** [comment]
I have done test node setup locally as well. Single node works fine, both local and AWS. Wanted multi-node architecture on AWS. Thanks for the information. Any idea when the new version will be available on AWS?
